package br.com.predialadm.classecon.condominio.enums;

public enum GrauInstrucaoEnum {
	ANALFABETO,
	FUNDAMENTAL_COMPLETO,
	FUNDAMENTAL_INCOMPLETO,
	ENSINO_MEDIO_COMPLETO,
	ENSINO_MEDIO_INCOMPLETO,
	SUPERIOR_COMPLETO,
	SUPERIOR_INCOMPLETO,
	ESPECIALISTA,
	MESTRE,
	DOUTOR;
}
